version: '3.1'

services:
  redis:
    image: redis


  db: 
    image: postgres:15-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    

  vote:
    image: voting-app
    ports: 
      - "5000:80"

  worker:
    image: worker-app
    depends_on:
      - db
      - redis

  result:
    image: result-app
    ports:
      - "5001:80"
    depends_on:
      - db
